[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "cryosbi"
authors = [
   { name = "David Silva-Sanchez", email = "david.silva@yale.edu"},
   { name = "Lars Dingeldein"},
   { name = "Pilar Cossio"},
   { name = "Roberto Covino"}
]


version = "0.2"
dependencies = [
    "lampe",
    "zuko",
    "torch",
    "numpy", 
    "matplotlib",
    "scipy",
    "torchvision",
    "mrcfile"
]


[project.scripts]
model_to_tensor = "cryo_sbi.utils.command_line_tools:cl_models_to_tensor"
model_to_tensor_topology = "cryo_sbi.utils.command_line_tools:cl_models_to_tensor_topology"
process_mrc_stack = "cryo_sbi.utils.command_line_tools:cl_process_mrc_stack"
estimate_param_simulation_from_star = "cryo_sbi.utils.command_line_tools:cl_estimate_param_simulation_from_star"
estimate_snr_from_mrc = "cryo_sbi.utils.command_line_tools:cl_estimate_snr_from_mrc"
pretrain_image_embed = "cryo_sbi.utils.command_line_tools:cl_pretrain_image_embed"
train_npe_model = "cryo_sbi.inference.command_line_tools:cl_npe_train_no_saving"
train_nle_model = "cryo_sbi.inference.command_line_tools:cl_nle_train_no_saving"
train_nle_model_with_validation = "cryo_sbi.inference.command_line_tools:cl_nle_train_no_saving_with_validation"
run_inference_real_data = "cryo_sbi.utils.command_line_tools:cl_run_inference_real_data"
run_inference_real_data_bayes = "cryo_sbi.utils.command_line_tools:cl_run_inference_real_data_bayes"
infer_populations = "cryo_sbi.utils.command_line_tools:cli_pinfer_populations"
